// Utilities for enhanced website preview functionality

export interface WebsitePreviewOptions {
  url: string;
  timeout?: number;
  retries?: number;
  screenshot?: boolean;
}

export interface PreviewResult {
  success: boolean;
  blocked: boolean;
  error?: string;
  screenshotUrl?: string;
  metadata?: {
    title?: string;
    description?: string;
    favicon?: string;
  };
}

/**
 * Enhanced iframe compatibility detection with progressive timeouts
 */
export const checkIframeCompatibility = async (url: string, timeout: number = 8000): Promise<{
  compatible: boolean;
  reason?: string;
  suggestions: string[];
}> => {
  try {
    // Use a more sophisticated approach with timeout control
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), timeout);
    
    const response = await fetch(url, { 
      method: 'HEAD',
      mode: 'no-cors',
      signal: controller.signal
    });
    
    clearTimeout(timeoutId);
    
    // Optimistic approach - assume compatible unless we detect specific issues
    return {
      compatible: true,
      suggestions: [
        'Website appears to be accessible',
        'iframe embedding should work',
        'Monitor for any security policy blocks'
      ]
    };
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    
    if (errorMessage.includes('abort')) {
      return {
        compatible: false,
        reason: `Website took longer than ${timeout/1000}s to respond`,
        suggestions: [
          'Try increasing the timeout duration',
          'Check if website is experiencing high traffic',
          'Use Widget Only mode as alternative'
        ]
      };
    }
    
    return {
      compatible: false,
      reason: errorMessage,
      suggestions: [
        'Check if the website URL is correct',
        'Verify network connectivity',
        'Try Widget Only preview mode'
      ]
    };
  }
};

/**
 * Extracts metadata from a website for preview purposes
 */
export const extractWebsiteMetadata = async (url: string): Promise<PreviewResult['metadata']> => {
  try {
    // In a real implementation, this would use a backend service to extract metadata
    // For now, we'll use basic URL parsing
    const domain = new URL(url).hostname;
    
    return {
      title: `Website Preview - ${domain}`,
      description: `Preview of ${domain}`,
      favicon: `https://www.google.com/s2/favicons?domain=${domain}&sz=32`
    };
  } catch (error) {
    console.error('Failed to extract metadata:', error);
    return {};
  }
};

/**
 * Generates alternative preview methods when iframe fails
 */
export const generateAlternativePreview = async (url: string): Promise<{
  screenshotUrl?: string;
  directUrl: string;
  embedCode: string;
}> => {
  // In production, integrate with screenshot services like:
  // - HTMLCSStoImage
  // - Screenshot API
  // - Puppeteer service
  
  const directUrl = url;
  const embedCode = `
    <!-- Alternative embed method -->
    <div id="website-preview" style="width: 100%; height: 600px; border: 1px solid #ccc;">
      <p>Click to view: <a href="${url}" target="_blank">${url}</a></p>
    </div>
  `;
  
  return {
    directUrl,
    embedCode,
    // screenshotUrl would be generated by a screenshot service
  };
};

/**
 * Detects heavy websites and provides optimization suggestions
 */
export const analyzeWebsitePerformance = (url: string): {
  isHeavy: boolean;
  suggestions: string[];
  optimizations: string[];
} => {
  const domain = new URL(url).hostname.toLowerCase();
  
  // List of known heavy site patterns
  const heavySitePatterns = [
    'wordpress.com',
    'wix.com',
    'squarespace.com',
    'shopify.com',
    '.gov.uk',
    '.gov',
    'hubspot.com'
  ];
  
  const isHeavy = heavySitePatterns.some(pattern => domain.includes(pattern));
  
  const suggestions = [
    'Consider using Widget Only preview for heavy sites',
    'Direct link preview as fallback option',
    'Screenshot-based preview for blocked sites'
  ];
  
  const optimizations = [
    'Implement lazy loading for preview generation',
    'Use progressive enhancement for widget loading',
    'Cache preview results to improve subsequent loads'
  ];
  
  return {
    isHeavy,
    suggestions: isHeavy ? suggestions : [],
    optimizations: isHeavy ? optimizations : []
  };
};

/**
 * Enhanced error handling for different preview failure types
 */
export const categorizePreviewError = (error: string): {
  category: 'security' | 'network' | 'timeout' | 'loading' | 'unknown';
  userMessage: string;
  technicalDetails: string;
  suggestions: string[];
} => {
  const errorLower = error.toLowerCase();
  
  if (errorLower.includes('x-frame-options') || errorLower.includes('csp') || errorLower.includes('security') || errorLower.includes('blocking')) {
    return {
      category: 'security',
      userMessage: 'Website blocks embedding for security reasons',
      technicalDetails: 'X-Frame-Options or Content Security Policy prevents iframe embedding',
      suggestions: [
        'Try the manual override option',
        'Use Widget Only preview instead',
        'Open website in new tab to verify it works directly'
      ]
    };
  }
  
  if (errorLower.includes('timeout') || errorLower.includes('abort') || errorLower.includes('took too long')) {
    return {
      category: 'timeout',
      userMessage: 'Website is taking longer than expected to load',
      technicalDetails: 'Request timeout - website may be slow or experiencing issues',
      suggestions: [
        'Try retry with longer timeout',
        'Check if website loads normally in new tab',
        'Use Widget Only preview as alternative'
      ]
    };
  }
  
  if (errorLower.includes('network') || errorLower.includes('fetch') || errorLower.includes('connection') || errorLower.includes('failed to load')) {
    return {
      category: 'network',
      userMessage: 'Unable to connect to website',
      technicalDetails: 'Network connectivity issue or website is down',
      suggestions: [
        'Check your internet connection',
        'Verify the website URL is correct',
        'Try again later if website is temporarily down'
      ]
    };
  }
  
  if (errorLower.includes('empty') || errorLower.includes('no content') || errorLower.includes('readystate')) {
    return {
      category: 'loading',
      userMessage: 'Website content is not loading properly',
      technicalDetails: 'Website may be loading slowly or have dynamic content',
      suggestions: [
        'Try retry with longer timeout',
        'Check if website loads normally in browser',
        'Some websites load content dynamically and may appear empty initially'
      ]
    };
  }
  
  return {
    category: 'unknown',
    userMessage: 'Preview encountered an unexpected issue',
    technicalDetails: error,
    suggestions: [
      'Try the manual override option',
      'Use Widget Only mode as fallback',
      'Open website directly in new tab'
    ]
  };
};

/**
 * Enhanced logging system for debugging preview issues
 */
export const createPreviewLogger = (context: string) => {
  const logs: string[] = [];
  
  return {
    log: (message: string, data?: any) => {
      const timestamp = new Date().toISOString();
      const logEntry = `[${timestamp}] ${context}: ${message}`;
      logs.push(logEntry);
      console.log(logEntry, data || '');
    },
    
    error: (message: string, error?: any) => {
      const timestamp = new Date().toISOString();
      const logEntry = `[${timestamp}] ${context} ERROR: ${message}`;
      logs.push(logEntry);
      console.error(logEntry, error || '');
    },
    
    getLogs: () => [...logs],
    
    clear: () => {
      logs.length = 0;
    }
  };
};

/**
 * Progressive retry strategy for iframe loading
 */
export const createRetryStrategy = (maxRetries: number = 3) => {
  let retryCount = 0;
  const baseTimeout = 5000;
  
  return {
    getTimeout: () => baseTimeout + (retryCount * 3000), // Increase timeout each retry
    
    canRetry: () => retryCount < maxRetries,
    
    nextRetry: () => {
      retryCount++;
      return {
        attempt: retryCount,
        timeout: baseTimeout + (retryCount * 3000),
        isLastAttempt: retryCount >= maxRetries
      };
    },
    
    reset: () => {
      retryCount = 0;
    },
    
    getStatus: () => ({
      attempt: retryCount,
      maxRetries,
      canRetry: retryCount < maxRetries
    })
  };
};